### ISSUE TITLE
[ISSUE] FATAL: password authentication failed for user "postgres" (28P01)

### ISSUE THREAD

**Issue by KOO-YS** [KOO-YS/quarkus-learning#3]
`docker-compose.yaml` 을 통해 PostgreSQL 컨테이너를 연동하다가 에러 발생

```
version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
```

<br>

### Error 
![image](https://user-images.githubusercontent.com/46165696/192543879-c7d4083e-ce39-4f0e-bc25-5bc0baceee54.png)

> **HR000021: DDL command failed [io.vertx.pgclient.PgException: FATAL: password authentication failed for user "postgres"**

<br>

<br>

---

<br>

### Solution 

**Command**
```
docker-compose down -v
```
➡️  Compose 정의 파일의 데이터 볼륨을 삭제

<br>

**데이터 볼륨을 삭제하기 전 terminal**
![image](https://user-images.githubusercontent.com/46165696/192544981-ced5eac3-21cd-4b6a-a2ce-f831d7267e66.png)

<br>

<br>

**데이터 볼륨을 삭제한 후 재실행한 terminal**
![image](https://user-images.githubusercontent.com/46165696/192545207-e6210b9a-ddf0-457e-aad7-82c919d4b15b.png)

<br>

정상적으로 연동 확인
![image](https://user-images.githubusercontent.com/46165696/192547555-25766c6f-2066-4bf6-933e-a46c1a031184.png)
